// Generated by gencpp from file extract_pose_service/object_and_target_position.msg
// DO NOT EDIT!


#ifndef EXTRACT_POSE_SERVICE_MESSAGE_OBJECT_AND_TARGET_POSITION_H
#define EXTRACT_POSE_SERVICE_MESSAGE_OBJECT_AND_TARGET_POSITION_H

#include <ros/service_traits.h>


#include <extract_pose_service/object_and_target_positionRequest.h>
#include <extract_pose_service/object_and_target_positionResponse.h>


namespace extract_pose_service
{

struct object_and_target_position
{

typedef object_and_target_positionRequest Request;
typedef object_and_target_positionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct object_and_target_position
} // namespace extract_pose_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::extract_pose_service::object_and_target_position > {
  static const char* value()
  {
    return "d051dd672e8e1f075426d8f6143b08a6";
  }

  static const char* value(const ::extract_pose_service::object_and_target_position&) { return value(); }
};

template<>
struct DataType< ::extract_pose_service::object_and_target_position > {
  static const char* value()
  {
    return "extract_pose_service/object_and_target_position";
  }

  static const char* value(const ::extract_pose_service::object_and_target_position&) { return value(); }
};


// service_traits::MD5Sum< ::extract_pose_service::object_and_target_positionRequest> should match
// service_traits::MD5Sum< ::extract_pose_service::object_and_target_position >
template<>
struct MD5Sum< ::extract_pose_service::object_and_target_positionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::extract_pose_service::object_and_target_position >::value();
  }
  static const char* value(const ::extract_pose_service::object_and_target_positionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::extract_pose_service::object_and_target_positionRequest> should match
// service_traits::DataType< ::extract_pose_service::object_and_target_position >
template<>
struct DataType< ::extract_pose_service::object_and_target_positionRequest>
{
  static const char* value()
  {
    return DataType< ::extract_pose_service::object_and_target_position >::value();
  }
  static const char* value(const ::extract_pose_service::object_and_target_positionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::extract_pose_service::object_and_target_positionResponse> should match
// service_traits::MD5Sum< ::extract_pose_service::object_and_target_position >
template<>
struct MD5Sum< ::extract_pose_service::object_and_target_positionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::extract_pose_service::object_and_target_position >::value();
  }
  static const char* value(const ::extract_pose_service::object_and_target_positionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::extract_pose_service::object_and_target_positionResponse> should match
// service_traits::DataType< ::extract_pose_service::object_and_target_position >
template<>
struct DataType< ::extract_pose_service::object_and_target_positionResponse>
{
  static const char* value()
  {
    return DataType< ::extract_pose_service::object_and_target_position >::value();
  }
  static const char* value(const ::extract_pose_service::object_and_target_positionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EXTRACT_POSE_SERVICE_MESSAGE_OBJECT_AND_TARGET_POSITION_H
