(cl:defpackage extract_pose_service-srv
  (:use )
  (:export
   "OBJECT_AND_TARGET_POSITION"
   "<OBJECT_AND_TARGET_POSITION-REQUEST>"
   "OBJECT_AND_TARGET_POSITION-REQUEST"
   "<OBJECT_AND_TARGET_POSITION-RESPONSE>"
   "OBJECT_AND_TARGET_POSITION-RESPONSE"
  ))

